'use client'
import {Inter} from "next/font/google";
import "./globals.scss";
import React, {Suspense} from "react";
import Loading from "./loading";
import Header from "../Components/Header";
import Footer from "../Components/Footer";
import SVG from "../Components/SVG";

const inter = Inter({subsets: ["latin"]});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({children}) {

    return (
        <html lang="en">
        <body className={inter.className}>
        <SVG />
        <Header/>
            {children}
        <Footer/>
        </body>
        </html>
    );
}
